site_name: "KENGI game engine: documentation"
site_url: https://kata.games/kengi-docs
repo_url: https://github.com/gaudiatech/kengi

nav:
    - Home: index.md
    - Version 2.x:
        - Getting Started: v2/getting-started.md
        - Types:
            - Comments: v2/types/comments.md
    - Version 1.x:
        - Types:
            - Comments: v1/types/comments.md
            - Posts: v1/types/posts.md

theme: readthedocs